### Send POST request with json body
POST http://localhost:8000/api/post/save
Content-Type: application/json

{
  "title":"Talk with god",
  "content":"Talk to god",
  "authorId":1,
  "team":{
    "id":1
  }
}