### Send POST request with json body
POST http://localhost:8000/api/reaction/save
Content-Type: application/json

{
  "post":
  {
    "id":1
  },
  "user":
  {
    "id":1
  },
  "reactionType":"like"
}